services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    env_file:
      - .env

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:5173:5173"

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db

    command: >
      sh -c "./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000"