GET http://localhost:8000/auth/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDQ5MTI5LCJpYXQiOjE3NDYwNDg4MjksImp0aSI6ImIwNjU5MDMwMGRkNTQ2ZmM4MjY2ZjQ1YzBiNzgxOTUxIiwidXNlcl9pZCI6MX0.g74XwdBQ4227DkTr91kJ7JgAlPBxClti9topbvBwcXo

###
POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type:  application/json

{
    "email": "presapplesang@gmail.com",
    "password": "lunalovegood"
}

###
POST http://localhost:8000/auth/jwt/refresh/ HTTP/1.1
Content-Type:  application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NjExMjc5MSwiaWF0IjoxNzQ2MDI2MzkxLCJqdGkiOiI1Njk4MjFlMjVjNmE0NTcxYjE4NzllNGM1YTRkMjNjNCIsInVzZXJfaWQiOjF9.DijYFP3l0dlqFg_xoGI0WV1v_WgKNmeOomp0NMqFD10"
}

###
POST http://localhost:8000/auth/users/ HTTP/1.1
Content-Type: application/json

{
  "email": "celeszhaianna@gmail.com",
  "password": "hello!"
  "re-pass"
}
